[package]
name = "migrations"
edition = "2021"

[[bin]]
name = "migrate"
path = "bin/migrate.rs"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["sea-orm-migration/cli"]
# will run tests that are really just quick smoke tests to ensure
# the migrations work for postgres
postgres-tests = []

[dependencies]
chrono = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

models = { path = "../models" }

[dev-dependencies]
testcontainers = { version = "0.27.0" }
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
