import { strToU8, unzipSync, zipSync } from 'fflate'

const GENERIC_ARCHIVE_URL = '/clients/coppice.koplugin.zip'
const CONFIG_PATH = 'coppice.koplugin/coppice_config.lua'
const DOWNLOAD_NAME = 'coppice.koplugin.zip'

function luaString(value: string): string {
	return `"${value
		.replaceAll('\\', '\\\\')
		.replaceAll('"', '\\"')
		.replaceAll('\r', '\\r')
		.replaceAll('\n', '\\n')}"`
}

function originOnly(value: string): string {
	const parsed = new URL(value)
	if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
		throw new Error('The Coppice plugin needs an http:// or https:// server origin.')
	}
	return parsed.origin
}

/**
 * Inject only the server origin and non-secret defaults into the generic plugin.
 * The returned bytes are suitable for a browser download and never contain a
 * username, API key, liseur token, pairing nonce, or password.
 */
export function buildCoppicePluginArchive(genericZip: Uint8Array, origin: string): Uint8Array {
	const files = unzipSync(genericZip)
	const pluginFiles = Object.keys(files).filter((path) => path.startsWith('coppice.koplugin/'))
	if (!pluginFiles.includes('coppice.koplugin/main.lua')) {
		throw new Error('The generic Coppice plugin archive is missing coppice.koplugin/main.lua.')
	}

	const server = originOnly(origin)
	files[CONFIG_PATH] = strToU8(
		[
			'-- Generated by Coppice Home. Origin and defaults only; never add credentials here.',
			'return {',
			`    server = ${luaString(server)},`,
			'    download_dir = nil,',
			'    device_name = "Coppice",',
			'}',
			'',
		].join('\n'),
	)
	return zipSync(files, { level: 6 })
}

/** Fetch, personalize, and download the generic Coppice plugin archive. */
export async function downloadCoppicePlugin(): Promise<void> {
	if (typeof window === 'undefined' || typeof document === 'undefined') return
	const response = await fetch(GENERIC_ARCHIVE_URL, { credentials: 'same-origin' })
	if (!response.ok)
		throw new Error(`The Coppice plugin archive could not be loaded (${response.status}).`)
	const archive = buildCoppicePluginArchive(
		new Uint8Array(await response.arrayBuffer()),
		window.location.origin,
	)
	const url = URL.createObjectURL(
		new Blob([archive.buffer as ArrayBuffer], { type: 'application/zip' }),
	)
	try {
		const anchor = document.createElement('a')
		anchor.href = url
		anchor.download = DOWNLOAD_NAME
		document.body.append(anchor)
		anchor.click()
		anchor.remove()
	} finally {
		setTimeout(() => URL.revokeObjectURL(url), 0)
	}
}
