[package]
name = "stump_opds"
version.workspace = true
edition = "2021"
description = "OPDS 1.2 and 2.0 compatibility routes for Stump"

[dependencies]
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
stump_api_types = { path = "../api-types" }
stump_auth = { path = "../auth" }
stump_core = { path = "../../core", default-features = false }
