use axum::{
	extract::{Path, Request, State},
	middleware::Next,
	response::{Json, Response},
	Extension,
};
use chrono::Utc;
use models::{
	domain::reading_state::{Position, ProtocolUpdate, Publication, SourceProtocol},
	entity::{device, media, reading_session},
	services::reading_progress::{upsert_reading_session, NormalizedProgression},
	shared::enums::{DeviceKind, UserPermission},
};
use sea_orm::{prelude::*, sea_query::OnConflict, Set, TransactionTrait};
use stump_core::reading_state;
use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;
use stump_auth::AuthContext;
use stump_devices::{CredentialRef, Protocol};

use crate::{
	config::state::AppState,
	errors::{APIError, APIResult},
};
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct KOReaderURLParams<D> {
	#[serde(flatten)]
	pub(crate) params: D,
	#[serde(default)]
	pub(crate) api_key: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct KOReaderDocumentURLParams {
	pub(crate) document: String,
}

// TODO(koreader): healthcheck? I don't think it is required, since I could configure Stump as a
// sync server just fine without it.

/// A secondary authorization middleware to ensure that the user has access to the
/// koreader sync endpoints. This is purely for convenience
pub(crate) async fn authorize(req: Request, next: Next) -> APIResult<Response> {
	let ctx = req
		.extensions()
		.get::<AuthContext>()
		.ok_or(APIError::Unauthorized)?;
	ctx.enforce_permissions(&[UserPermission::AccessKoreaderSync])
		.map_err(|_| {
			APIError::Forbidden(
				"You do not have permission to use KOReader sync".to_string(),
			)
		})?;
	Ok(next.run(req).await)
}

#[derive(Serialize)]
pub(crate) struct CheckAuthorizedResponse {
	pub(crate) authorized: String,
}

pub(crate) async fn check_authorized() -> APIResult<Json<CheckAuthorizedResponse>> {
	Ok(Json(CheckAuthorizedResponse {
		authorized: "OK".to_string(),
	}))
}

#[skip_serializing_none]
#[derive(Default, Serialize, Deserialize)]
pub(crate) struct GetProgressResponse {
	/// A hash of the book, generated by koreader. This is used as an alternative method for
	/// identifying a book, since koreader is unaware of the book's ID in stump
	document: String,
	/// A string representing the current position in the book, as understood by koreader. This
	/// can be one of two things:
	///
	/// - A page number for page-based books (e.g. "24")
	/// - An x-pointer for DOM-based books, using their "scrolling" reader. This maps to the location
	///   in the DOM at the top of the screen at the time of sync. This is not a Readium locator.
	///
	/// Please see this wonderful comment for additional context: https://github.com/stumpapp/stump/issues/239#issuecomment-2428256328
	progress: Option<String>,
	/// The reading progress of the book, as a percentage (0-1.0)
	percentage: Option<f32>,
	/// The name of the koreader device.
	device: Option<String>,
	/// The ID of the koreader device, generated by koreader. Stump will use this to identify a
	/// registered reading device, if one exists with the ID.
	device_id: Option<String>,
	/// The timestamp of the last progress update, in milliseconds since the Unix epoch.
	timestamp: Option<u64>,
}

pub(crate) async fn get_progress(
	State(ctx): State<AppState>,
	Extension(req): Extension<AuthContext>,
	Path(KOReaderURLParams {
		params: KOReaderDocumentURLParams { document },
		..
	}): Path<KOReaderURLParams<KOReaderDocumentURLParams>>,
) -> APIResult<Json<GetProgressResponse>> {
	let conn = ctx.conn.as_ref();
	let user = req.user();

	let book = media::Entity::find()
		.filter(media::Column::KoreaderHash.eq(document.clone()))
		.one(conn)
		.await?;
	let head = match &book {
		Some(book) => reading_state::head(conn, &user.id, &book.id).await?,
		None => None,
	};
	let Some(head) = head else {
		return Ok(Json(GetProgressResponse {
			document,
			..Default::default()
		}));
	};

	let device = match head.source_device_id.as_deref() {
		Some(id) => device::Entity::find_by_id(id).one(conn).await?,
		None => None,
	};
	// KOReader's own position (an x-pointer or a page string) is replayed
	// verbatim when this lane produced the head; otherwise the head page is
	// the only coordinate KOReader can use.
	let winning = reading_state::winning_event(conn, &head).await?;
	let native_progress = winning
		.filter(|event| event.protocol == SourceProtocol::Koreader)
		.and_then(|event| event.raw_payload.get("progress")?.as_str().map(String::from));
	let progress = match (head.completed, native_progress, head.page) {
		(_, Some(native), _) => Some(native),
		(_, None, Some(page)) => Some(page.to_string()),
		_ => None,
	};
	let progress = GetProgressResponse {
		document,
		percentage: Some(head.progression as f32),
		timestamp: Some(head.updated_at.timestamp_millis() as u64),
		device: device.as_ref().map(|d| d.name.clone()),
		device_id: device.as_ref().map(|d| d.id.clone()),
		progress,
	};

	Ok(Json(progress))
}

/// KoReader's non-numeric progress formats (such as x-pointers) are retained
/// verbatim on the session but cannot be mapped to Stump's page coordinate.
fn parse_progress(progress: &str) -> Option<i32> {
	progress.parse().ok() // Try to parse as a page number
}

#[derive(Deserialize)]
pub(crate) struct PutProgressInput {
	pub(crate) document: String,
	pub(crate) progress: String,
	pub(crate) percentage: f32,
	pub(crate) device: String,
	pub(crate) device_id: String,
}

#[derive(Deserialize, Serialize)]
pub(crate) struct PutProgressResponse {
	document: String,
	timestamp: u64,
}

pub(crate) async fn put_progress(
	State(ctx): State<AppState>,
	Extension(req): Extension<AuthContext>,
	Json(PutProgressInput {
		document,
		progress,
		percentage,
		device,
		device_id,
	}): Json<PutProgressInput>,
) -> APIResult<Json<PutProgressResponse>> {
	let conn = ctx.conn.as_ref();
	let user = req.user();

	if !(0.0..=1.0).contains(&percentage) {
		tracing::error!(
			percentage,
			"Invalid percentage provided for progress update"
		);
		return Err(APIError::BadRequest("Invalid percentage".to_string()));
	}
	tracing::debug!(?percentage, book_hash = ?document, "Got PUT KoReader payload");

	let book = media::Entity::find()
		.filter(media::Column::KoreaderHash.eq(document.clone()))
		.one(conn)
		.await?
		.ok_or_else(|| APIError::NotFound("Book not found".to_string()))?;

	let is_completed = percentage >= 1.0;

	let tx = ctx.conn.as_ref().begin().await?;

	// KOReader identifies itself by a device id + name on every push; register
	// it as a device of the syncing user (name follows KOReader's setting).
	let on_conflict = OnConflict::column(device::Column::Id)
		.update_columns([device::Column::Name, device::Column::LastSeenAt])
		.to_owned();

	let _device_record = device::Entity::insert(device::ActiveModel {
		id: Set(device_id.clone()),
		user_id: Set(user.id.clone()),
		name: Set(device.clone()),
		kind: Set(DeviceKind::Koreader),
		last_seen_at: Set(Some(Utc::now().into())),
		..Default::default()
	})
	.on_conflict(on_conflict)
	.exec(&tx)
	.await?;

	let page = parse_progress(&progress);
	if page.is_none() {
		tracing::debug!(
			progress,
			"Failed to parse progress string, assuming x-pointer"
		);
	}
	let progression = NormalizedProgression {
		page,
		percentage: Decimal::try_from(percentage).ok(),
		did_complete: is_completed,
		device_id: Some(device_id.clone()),
		..Default::default()
	};

	let session =
		upsert_reading_session(&tx, &user, book.id.as_ref(), progression).await?;

	if session.koreader_progress.as_deref() != Some(progress.as_str()) {
		let mut active: reading_session::ActiveModel = session.into();
		active.koreader_progress = Set(Some(progress.clone()));
		active.update(&tx).await?;
	}

	let applied = reading_state::apply(
		&tx,
		&user.id,
		Publication::from(&book),
		ProtocolUpdate {
			protocol: SourceProtocol::Koreader,
			device_id: Some(device_id.clone()),
			updated_at: None,
			position: page.map_or(Position::None, Position::Page),
			progression: Some(f64::from(percentage)),
			completed: is_completed.then_some(true),
			raw_payload: serde_json::json!({
				"document": document,
				"progress": progress,
				"percentage": percentage,
				"device": device,
				"device_id": device_id,
			}),
		},
	)
	.await?;

	tx.commit().await?;
	reading_state::announce(&ctx, &book, &applied);

	// Record the sync on the device this key belongs to; the sync itself must
	// never fail because of the registry.
	if let Some(api_key) = req.api_key() {
		let sync_summary = serde_json::json!({
			"protocol": "koreader",
			"document": document,
			"progress": progress,
			"percentage": percentage,
			"koreader_device": device,
			"koreader_device_id": device_id,
		});
		if let Err(error) = ctx
			.devices()
			.touch(
				CredentialRef::ApiKey(&api_key),
				Protocol::Koreader,
				Some(sync_summary),
			)
			.await
		{
			tracing::warn!(?error, "Failed to record the KOReader sync on its device");
		}
	}

	Ok(Json(PutProgressResponse {
		document,
		// not exact but i'm sure it's fine
		timestamp: Utc::now().timestamp_millis() as u64,
	}))
}
