//! async-graphql schema for the web/desktop/mobile clients (server feature
//! `graphql`; absent from `minimal`). `schema.graphql` is generated by the
//! `graphql-gen` binary (`cargo dump-schema`) and checked in CI.
//! See `crates/graphql/README.md`.

pub mod data;
pub(crate) mod error;
pub mod error_message;
pub mod filter;
pub mod guard;
pub mod input;
pub mod loader;
pub mod mutation;
pub mod object;
pub mod order;
pub mod pagination;
pub mod query;
pub mod schema;
pub mod subscription;
pub(crate) mod utils;

#[cfg(test)]
mod tests;

// TODO: Look into https://async-graphql.github.io/async-graphql/en/extensions_available.html#tracing
// TODO: Look into https://async-graphql.github.io/async-graphql/en/extensions_available.html#apollo-persisted-queries
// TODO: Look into data loaders: https://async-graphql.github.io/async-graphql/en/dataloader.html
