//! Durable private book-request lifecycle rows.
//!
//! The request ledger deliberately stores normalized release facts and opaque
//! gateway handles only. Tracker cookies, raw download URLs, and provider
//! credentials remain inside the private mam-gateway sidecar.

use sea_orm::sea_query::Expr;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.create_table(
				Table::create()
					.table(BookRequests::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequests::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(ColumnDef::new(BookRequests::RequesterId).text().not_null())
					.col(ColumnDef::new(BookRequests::InternalMediaId).text().null())
					.col(ColumnDef::new(BookRequests::InternalWorkId).text().null())
					.col(ColumnDef::new(BookRequests::SourceProvider).text().null())
					.col(ColumnDef::new(BookRequests::RemoteId).text().null())
					.col(ColumnDef::new(BookRequests::ExternalKey).text().null())
					.col(ColumnDef::new(BookRequests::Title).text().not_null())
					.col(ColumnDef::new(BookRequests::Authors).text().null())
					.col(ColumnDef::new(BookRequests::CoverUrl).text().null())
					.col(
						ColumnDef::new(BookRequests::DestinationShelfId)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequests::DestinationDeviceId)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequests::Status)
							.text()
							.not_null()
							.default("PENDING"),
					)
					.col(
						ColumnDef::new(BookRequests::ApprovalPolicy)
							.text()
							.not_null()
							.default("REQUIRED"),
					)
					.col(
						ColumnDef::new(BookRequests::AutomationEnabled)
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(BookRequests::ScoringFloor)
							.integer()
							.not_null()
							.default(80),
					)
					.col(
						ColumnDef::new(BookRequests::VerificationThreshold)
							.integer()
							.not_null()
							.default(70),
					)
					.col(
						ColumnDef::new(BookRequests::MaxRetries)
							.integer()
							.not_null()
							.default(3),
					)
					.col(
						ColumnDef::new(BookRequests::Retries)
							.integer()
							.not_null()
							.default(0),
					)
					.col(ColumnDef::new(BookRequests::ApprovedBy).text().null())
					.col(ColumnDef::new(BookRequests::RejectedBy).text().null())
					.col(ColumnDef::new(BookRequests::FailureCode).text().null())
					.col(ColumnDef::new(BookRequests::FailureMessage).text().null())
					.col(
						ColumnDef::new(BookRequests::CreatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(BookRequests::UpdatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(BookRequests::ApprovedAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequests::CompletedAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-requests-requester")
							.from(BookRequests::Table, BookRequests::RequesterId)
							.to(Users::Table, Users::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("idx-book-requests-requester-status")
					.table(BookRequests::Table)
					.col(BookRequests::RequesterId)
					.col(BookRequests::Status)
					.to_owned(),
			)
			.await?;

		manager
			.create_table(
				Table::create()
					.table(BookRequestSearches::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequestSearches::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(
						ColumnDef::new(BookRequestSearches::RequestId)
							.text()
							.not_null(),
					)
					.col(ColumnDef::new(BookRequestSearches::Query).text().not_null())
					.col(
						ColumnDef::new(BookRequestSearches::Provider)
							.text()
							.not_null()
							.default("mam"),
					)
					.col(
						ColumnDef::new(BookRequestSearches::Status)
							.text()
							.not_null()
							.default("PENDING"),
					)
					.col(
						ColumnDef::new(BookRequestSearches::ResultCount)
							.integer()
							.not_null()
							.default(0),
					)
					.col(ColumnDef::new(BookRequestSearches::ErrorCode).text().null())
					.col(
						ColumnDef::new(BookRequestSearches::ErrorMessage)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestSearches::StartedAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestSearches::FinishedAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestSearches::CreatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-searches-request")
							.from(
								BookRequestSearches::Table,
								BookRequestSearches::RequestId,
							)
							.to(BookRequests::Table, BookRequests::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;

		manager
			.create_table(
				Table::create()
					.table(BookRequestReleases::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequestReleases::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::SearchId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::RequestId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::SourceProvider)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::RemoteId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::ExternalKey)
							.text()
							.null(),
					)
					.col(ColumnDef::new(BookRequestReleases::Title).text().not_null())
					.col(ColumnDef::new(BookRequestReleases::Authors).text().null())
					.col(ColumnDef::new(BookRequestReleases::Format).text().null())
					.col(ColumnDef::new(BookRequestReleases::Language).text().null())
					.col(ColumnDef::new(BookRequestReleases::Edition).text().null())
					.col(ColumnDef::new(BookRequestReleases::Quality).text().null())
					.col(
						ColumnDef::new(BookRequestReleases::SizeBytes)
							.big_integer()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::Seeders)
							.integer()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::PreviewName)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::PreviewMime)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::PreviewBytes)
							.big_integer()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::Score)
							.integer()
							.not_null()
							.default(0),
					)
					.col(
						ColumnDef::new(BookRequestReleases::ScoreComponents)
							.json()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestReleases::Rank)
							.integer()
							.not_null()
							.default(0),
					)
					.col(
						ColumnDef::new(BookRequestReleases::Selected)
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(BookRequestReleases::CreatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-releases-search")
							.from(
								BookRequestReleases::Table,
								BookRequestReleases::SearchId,
							)
							.to(BookRequestSearches::Table, BookRequestSearches::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-releases-request")
							.from(
								BookRequestReleases::Table,
								BookRequestReleases::RequestId,
							)
							.to(BookRequests::Table, BookRequests::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("idx-book-request-releases-request-rank")
					.table(BookRequestReleases::Table)
					.col(BookRequestReleases::RequestId)
					.col(BookRequestReleases::Rank)
					.to_owned(),
			)
			.await?;

		manager
			.create_table(
				Table::create()
					.table(BookRequestApprovals::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequestApprovals::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(
						ColumnDef::new(BookRequestApprovals::RequestId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestApprovals::ApproverId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestApprovals::Decision)
							.text()
							.not_null(),
					)
					.col(ColumnDef::new(BookRequestApprovals::Reason).text().null())
					.col(
						ColumnDef::new(BookRequestApprovals::CreatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-approvals-request")
							.from(
								BookRequestApprovals::Table,
								BookRequestApprovals::RequestId,
							)
							.to(BookRequests::Table, BookRequests::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-approvals-approver")
							.from(
								BookRequestApprovals::Table,
								BookRequestApprovals::ApproverId,
							)
							.to(Users::Table, Users::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;

		manager
			.create_table(
				Table::create()
					.table(BookRequestGrabs::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequestGrabs::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::RequestId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::ReleaseId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::OpaqueId)
							.text()
							.not_null()
							.unique_key(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::Status)
							.text()
							.not_null()
							.default("PENDING"),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::Attempts)
							.integer()
							.not_null()
							.default(0),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::MaxAttempts)
							.integer()
							.not_null()
							.default(3),
					)
					.col(ColumnDef::new(BookRequestGrabs::FailureCode).text().null())
					.col(
						ColumnDef::new(BookRequestGrabs::FailureMessage)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::StartedAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::FinishedAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::LastPolledAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::NextPollAt)
							.timestamp_with_time_zone()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::CreatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(BookRequestGrabs::UpdatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-grabs-request")
							.from(BookRequestGrabs::Table, BookRequestGrabs::RequestId)
							.to(BookRequests::Table, BookRequests::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-grabs-release")
							.from(BookRequestGrabs::Table, BookRequestGrabs::ReleaseId)
							.to(BookRequestReleases::Table, BookRequestReleases::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;

		manager
			.create_table(
				Table::create()
					.table(BookRequestHandoffs::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequestHandoffs::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::RequestId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::GrabId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::LibraryId)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::RelativePath)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::Sha256)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::ByteSize)
							.big_integer()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::Status)
							.text()
							.not_null()
							.default("RECEIVED"),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::DropItemId)
							.text()
							.null(),
					)
					.col(ColumnDef::new(BookRequestHandoffs::ShelfId).text().null())
					.col(ColumnDef::new(BookRequestHandoffs::DeviceId).text().null())
					.col(ColumnDef::new(BookRequestHandoffs::ErrorCode).text().null())
					.col(
						ColumnDef::new(BookRequestHandoffs::ErrorMessage)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::CreatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.col(
						ColumnDef::new(BookRequestHandoffs::UpdatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-handoffs-request")
							.from(
								BookRequestHandoffs::Table,
								BookRequestHandoffs::RequestId,
							)
							.to(BookRequests::Table, BookRequests::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.foreign_key(
						ForeignKey::create()
							.name("fk-book-request-handoffs-grab")
							.from(BookRequestHandoffs::Table, BookRequestHandoffs::GrabId)
							.to(BookRequestGrabs::Table, BookRequestGrabs::Id)
							.on_delete(ForeignKeyAction::Cascade)
							.on_update(ForeignKeyAction::Cascade),
					)
					.to_owned(),
			)
			.await?;

		manager
			.create_table(
				Table::create()
					.table(BookRequestGatewaySettings::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(BookRequestGatewaySettings::Id)
							.text()
							.not_null()
							.primary_key(),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::Endpoint)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::EncryptedToken)
							.text()
							.not_null(),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::Enabled)
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::RequireApproval)
							.boolean()
							.not_null()
							.default(true),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::AutomationEnabled)
							.boolean()
							.not_null()
							.default(false),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::ScoringFloor)
							.integer()
							.not_null()
							.default(80),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::VerificationThreshold)
							.integer()
							.not_null()
							.default(70),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::MaxRetries)
							.integer()
							.not_null()
							.default(3),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::HandoffRoot)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::UpdatedBy)
							.text()
							.null(),
					)
					.col(
						ColumnDef::new(BookRequestGatewaySettings::UpdatedAt)
							.timestamp_with_time_zone()
							.not_null()
							.default(Expr::current_timestamp()),
					)
					.to_owned(),
			)
			.await?;
		Ok(())
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.drop_table(
				Table::drop()
					.table(BookRequestGatewaySettings::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(
				Table::drop()
					.table(BookRequestHandoffs::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(
				Table::drop()
					.table(BookRequestGrabs::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(
				Table::drop()
					.table(BookRequestApprovals::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(
				Table::drop()
					.table(BookRequestReleases::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(
				Table::drop()
					.table(BookRequestSearches::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		manager
			.drop_table(
				Table::drop()
					.table(BookRequests::Table)
					.if_exists()
					.to_owned(),
			)
			.await?;
		Ok(())
	}
}

#[derive(DeriveIden)]
enum Users {
	Table,
	Id,
}

#[derive(DeriveIden)]
enum BookRequests {
	Table,
	Id,
	RequesterId,
	InternalMediaId,
	InternalWorkId,
	SourceProvider,
	RemoteId,
	ExternalKey,
	Title,
	Authors,
	CoverUrl,
	DestinationShelfId,
	DestinationDeviceId,
	Status,
	ApprovalPolicy,
	AutomationEnabled,
	ScoringFloor,
	VerificationThreshold,
	MaxRetries,
	Retries,
	ApprovedBy,
	RejectedBy,
	FailureCode,
	FailureMessage,
	CreatedAt,
	UpdatedAt,
	ApprovedAt,
	CompletedAt,
}

#[derive(DeriveIden)]
enum BookRequestSearches {
	Table,
	Id,
	RequestId,
	Query,
	Provider,
	Status,
	ResultCount,
	ErrorCode,
	ErrorMessage,
	StartedAt,
	FinishedAt,
	CreatedAt,
}

#[derive(DeriveIden)]
enum BookRequestReleases {
	Table,
	Id,
	SearchId,
	RequestId,
	SourceProvider,
	RemoteId,
	ExternalKey,
	Title,
	Authors,
	Format,
	Language,
	Edition,
	Quality,
	SizeBytes,
	Seeders,
	PreviewName,
	PreviewMime,
	PreviewBytes,
	Score,
	ScoreComponents,
	Rank,
	Selected,
	CreatedAt,
}

#[derive(DeriveIden)]
enum BookRequestApprovals {
	Table,
	Id,
	RequestId,
	ApproverId,
	Decision,
	Reason,
	CreatedAt,
}

#[derive(DeriveIden)]
enum BookRequestGrabs {
	Table,
	Id,
	RequestId,
	ReleaseId,
	OpaqueId,
	Status,
	Attempts,
	MaxAttempts,
	FailureCode,
	FailureMessage,
	StartedAt,
	FinishedAt,
	LastPolledAt,
	NextPollAt,
	CreatedAt,
	UpdatedAt,
}

#[derive(DeriveIden)]
enum BookRequestHandoffs {
	Table,
	Id,
	RequestId,
	GrabId,
	LibraryId,
	RelativePath,
	Sha256,
	ByteSize,
	Status,
	DropItemId,
	ShelfId,
	DeviceId,
	ErrorCode,
	ErrorMessage,
	CreatedAt,
	UpdatedAt,
}

#[derive(DeriveIden)]
enum BookRequestGatewaySettings {
	Table,
	Id,
	Endpoint,
	EncryptedToken,
	Enabled,
	RequireApproval,
	AutomationEnabled,
	ScoringFloor,
	VerificationThreshold,
	MaxRetries,
	HandoffRoot,
	UpdatedBy,
	UpdatedAt,
}
