[package]
name = "stump_kepub"
version.workspace = true
edition = "2021"
description = "Pure Rust EPUB to Kobo KEPUB conversion"

[dependencies]
html5ever = "0.26.0"
markup5ever = "0.11.0"
quick-xml.workspace = true
rayon = "1.10"
sha2 = "0.10.9"
thiserror.workspace = true
zip.workspace = true
libdeflater = "1.26"

[dev-dependencies]
tempfile.workspace = true
markup5ever_rcdom = "0.2.0"
